import os

from tornado.options import options, define


HERE = os.path.dirname(__file__)


define('port', 7007, help='The default port for the SSSSG app')
define('cache_file_directory', HERE + '/../caches', help=('the directory'
    ' where to write the cache files generated by SSSSG'))
define('four_oh_four', os.path.join(HERE, 'pages', '404.md'),
    help='The default 404 page to render')
define('five_oh_oh', os.path.join(HERE, 'pages', '500.md'),
    help='The default 500 page to render')
define('base_template', os.path.join(HERE, 'pages', 'base.html'),
    help='The default template to use when rendering a page')
define('search_template', os.path.join(HERE, 'pages', 'search.html'),
    help='The default template to use when rendering search results')
define('default_error_title', 'Server Error',
    help='The default title to show when there is an error rendering the page')
define('debug', True, help='Hot-reload or not')
